[package]
name = "miniscript"
version = "0.11.0"
authors = ["Andrew Poelstra <apoelstra@wpsoftware.net>"]
repository = "https://github.com/apoelstra/miniscript"
description = "Miniscript: a subset of Bitcoin Script designed for analysis"
license = "CC0-1.0"

[features]
fuzztarget = ["bitcoin/fuzztarget"]
compiler = []
trace = []
unstable = []
default = []

[dependencies]
bitcoin = { git = "git://github.com/stevenroose/rust-bitcoin", branch = "devel" }

[dependencies.serde]
version = "1.0"
optional = true

[[example]]
name = "htlc"
required-features = ["compiler"]

[[example]]
name = "parse"

[[example]]
name = "sign_multisig"

[[example]]
name = "verify_tx"
